# Generated by Django 2.2.10 on 2021-07-15 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Poll name')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('end', models.DateTimeField(verbose_name='End date')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Question text')),
                ('type', models.CharField(choices=[('text', 'Text answer'), ('chose_one', 'Answer with one choise'), ('chose_many', 'Answer with many choise')], max_length=23, verbose_name='Question type')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingSystem.Polls', verbose_name='Question poll')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingSystem.Answers', verbose_name='User answer')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingSystem.Polls', verbose_name='Passed poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingSystem.Questions', verbose_name='Answered question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingSystem.Questions', verbose_name='Answer question'),
        ),
    ]
